# Generated by Django 5.1.13 on 2025-10-25 05:53

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Home Page"},
        ),
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("paragraph", 1), ("image", 2), ("html", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "help_text": "Section heading"},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Paragraph text with formatting"},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Full-width image"},
                    ),
                    3: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {"help_text": "Raw HTML content (use with caution)"},
                    ),
                },
                help_text="Main page content",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="canonical_url",
            field=models.URLField(
                blank=True,
                help_text="Override canonical URL (leave blank to use page URL)",
                verbose_name="Canonical URL",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero",
            field=wagtail.fields.StreamField(
                [("banner", 12), ("slider", 29), ("video", 40), ("parallax", 46)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Override page title (leave blank to use page title)",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle or tagline", "max_length": 255, "required": False},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Desktop image (1920x600px recommended)", "required": False},
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Tablet image (1024x600px recommended) - Optional",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Mobile image (768x600px recommended) - Falls back to desktop if not provided",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small (400px)"),
                                ("medium", "Medium (600px)"),
                                ("large", "Large (800px)"),
                                ("full", "Full Screen"),
                            ],
                            "help_text": "Banner height on desktop",
                        },
                    ),
                    6: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 30,
                            "help_text": "Dark overlay opacity (0-100) - Helps text readability",
                            "max_value": 100,
                            "min_value": 0,
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "help_text": "Text alignment in banner",
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("white", "White"), ("black", "Black")],
                            "help_text": "Text color",
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Button text", "max_length": 50, "required": False},
                    ),
                    10: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link to internal page", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Or link to external URL (overrides page link)",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("image", 2),
                                ("image_tablet", 3),
                                ("image_mobile", 4),
                                ("height", 5),
                                ("overlay_opacity", 6),
                                ("text_alignment", 7),
                                ("text_color", 8),
                                ("cta_text", 9),
                                ("cta_link", 10),
                                ("cta_external", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Slide title", "max_length": 255, "required": False},
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Slide subtitle", "max_length": 255, "required": False},
                    ),
                    15: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Desktop image (1920x600px)", "required": True},
                    ),
                    16: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Tablet image (1024x600px) - Optional", "required": False},
                    ),
                    17: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Mobile image (768x600px) - Optional", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Or external URL", "required": False},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 13),
                                ("subtitle", 14),
                                ("image", 15),
                                ("image_tablet", 16),
                                ("image_mobile", 17),
                                ("cta_text", 9),
                                ("cta_link", 10),
                                ("cta_external", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.ListBlock",
                        (19,),
                        {"help_text": "Add 2-10 slides", "max_num": 10, "min_num": 2},
                    ),
                    21: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "help_text": "Auto-advance slides", "required": False},
                    ),
                    22: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 5000,
                            "help_text": "Milliseconds between slides (1000 = 1 second)",
                            "max_value": 10000,
                            "min_value": 1000,
                        },
                    ),
                    23: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show previous/next arrows",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "help_text": "Show navigation dots", "required": False},
                    ),
                    25: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small (400px)"),
                                ("medium", "Medium (600px)"),
                                ("large", "Large (800px)"),
                                ("full", "Full Screen"),
                            ]
                        },
                    ),
                    26: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 30,
                            "help_text": "Dark overlay opacity (0-100)",
                            "max_value": 100,
                            "min_value": 0,
                        },
                    ),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("left", "Left"), ("center", "Center"), ("right", "Right")]},
                    ),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("white", "White"), ("black", "Black")]},
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("slides", 20),
                                ("autoplay", 21),
                                ("autoplay_speed", 22),
                                ("show_arrows", 23),
                                ("show_dots", 24),
                                ("height", 25),
                                ("overlay_opacity", 26),
                                ("text_alignment", 27),
                                ("text_color", 28),
                            ]
                        ],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "YouTube or Vimeo URL (e.g., https://www.youtube.com/watch?v=...)",
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Fallback image shown while loading or if video fails (1920x1080px)",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title overlaid on video",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Subtitle overlaid on video",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Auto-play video on page load",
                            "required": False,
                        },
                    ),
                    35: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Loop video continuously",
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Mute video (must be muted for autoplay to work)",
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "help_text": "Show video controls", "required": False},
                    ),
                    38: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("medium", "Medium (600px)"),
                                ("large", "Large (800px)"),
                                ("full", "Full Screen"),
                            ],
                            "help_text": "Video banner height",
                        },
                    ),
                    39: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 40,
                            "help_text": "Dark overlay opacity (0-100)",
                            "max_value": 100,
                            "min_value": 0,
                        },
                    ),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("video_url", 30),
                                ("poster_image", 31),
                                ("title", 32),
                                ("subtitle", 33),
                                ("autoplay", 34),
                                ("loop", 35),
                                ("muted", 36),
                                ("show_controls", 37),
                                ("height", 38),
                                ("overlay_opacity", 39),
                                ("text_alignment", 27),
                                ("text_color", 28),
                                ("cta_text", 9),
                                ("cta_link", 10),
                                ("cta_external", 18),
                            ]
                        ],
                        {},
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Banner title", "max_length": 255, "required": False},
                    ),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Banner subtitle", "max_length": 255, "required": False},
                    ),
                    43: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Large background image (2400x1200px recommended for best parallax effect)",
                            "required": True,
                        },
                    ),
                    44: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("slow", "Slow (0.3x)"),
                                ("medium", "Medium (0.5x)"),
                                ("fast", "Fast (0.7x)"),
                            ],
                            "help_text": "Parallax scroll speed",
                        },
                    ),
                    45: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("medium", "Medium (600px)"),
                                ("large", "Large (800px)"),
                                ("full", "Full Screen"),
                            ]
                        },
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 41),
                                ("subtitle", 42),
                                ("background_image", 43),
                                ("parallax_speed", 44),
                                ("height", 45),
                                ("overlay_opacity", 26),
                                ("text_alignment", 27),
                                ("text_color", 28),
                                ("cta_text", 9),
                                ("cta_link", 10),
                                ("cta_external", 18),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Choose one hero type for the top of the page (optional)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="no_follow",
            field=models.BooleanField(
                default=False,
                help_text="Prevent search engines from following links on this page",
                verbose_name="No follow",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="no_index",
            field=models.BooleanField(
                default=False,
                help_text="Prevent search engines from indexing this page",
                verbose_name="No index",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image for social media sharing (1200x630px recommended)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Social media image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="twitter_card_type",
            field=models.CharField(
                blank=True,
                choices=[("summary", "Summary"), ("summary_large_image", "Summary Large Image")],
                default="summary_large_image",
                help_text="Type of Twitter card to use",
                max_length=20,
                verbose_name="Twitter card type",
            ),
        ),
    ]
