# Generated by Django 5.1.13 on 2025-10-25 12:35

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_homepage_meta_description"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("image", 2),
                    ("image_with_content", 10),
                    ("faq", 17),
                    ("accordion", 21),
                    ("get_in_touch", 29),
                    ("html", 30),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "help_text": "Section heading"},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Paragraph text with formatting"},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Full-width image"},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Section title", "max_length": 255},
                    ),
                    4: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Content text with formatting support"},
                    ),
                    5: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Image (recommended: 600x400px)"},
                    ),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("left", "Image on Left"), ("right", "Image on Right")]},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Button text", "max_length": 50, "required": False},
                    ),
                    8: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    9: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 3),
                                ("description", 4),
                                ("image", 5),
                                ("image_position", 6),
                                ("link_text", 7),
                                ("link_page", 8),
                                ("link_external", 9),
                            ]
                        ],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Section title", "max_length": 255, "required": False},
                    ),
                    12: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Section description", "required": False},
                    ),
                    13: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                    14: ("wagtail.blocks.RichTextBlock", (), {}),
                    15: ("wagtail.blocks.StructBlock", [[("question", 13), ("answer", 14)]], {}),
                    16: (
                        "wagtail.blocks.ListBlock",
                        (15,),
                        {"help_text": "Add 1-20 FAQ items", "max_num": 20, "min_num": 1},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 11), ("description", 12), ("faqs", 16)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("description", 14)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.ListBlock",
                        (18,),
                        {"help_text": "Add 1-20 accordion items", "max_num": 20, "min_num": 1},
                    ),
                    20: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Allow multiple items to be open at once",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 11),
                                ("description", 12),
                                ("items", 19),
                                ("allow_multiple_open", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Get In Touch",
                            "help_text": "Section title",
                            "max_length": 255,
                        },
                    ),
                    23: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Section description"}),
                    24: (
                        "wagtail.blocks.EmailBlock",
                        (),
                        {"help_text": "Contact email", "required": False},
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Contact phone number", "max_length": 20, "required": False},
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Contact address", "max_length": 255, "required": False},
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Contact Us", "help_text": "Button text", "max_length": 50},
                    ),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary Color"),
                                ("secondary", "Secondary Color"),
                                ("light", "Light Gray"),
                                ("dark", "Dark Gray"),
                            ],
                            "help_text": "Background color",
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 22),
                                ("description", 23),
                                ("email", 24),
                                ("phone", 25),
                                ("address", 26),
                                ("cta_text", 27),
                                ("cta_link", 8),
                                ("cta_external", 9),
                                ("background_color", 28),
                            ]
                        ],
                        {},
                    ),
                    30: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {"help_text": "Raw HTML content (use with caution)"},
                    ),
                },
                help_text="Main page content",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="canonical_url",
            field=models.URLField(
                blank=True, help_text="Canonical URL (leave blank to use page URL)"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero",
            field=wagtail.fields.StreamField(
                [("banner", 12), ("slider", 22), ("video", 25), ("parallax", 29)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Override page title (leave blank to use page title)",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Subtitle or tagline", "max_length": 255, "required": False},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Desktop image (1920x600px recommended)", "required": False},
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Tablet image (1024x600px recommended) - Optional",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Mobile image (768x600px recommended) - Falls back to desktop if not provided",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small (400px)"),
                                ("medium", "Medium (600px)"),
                                ("large", "Large (800px)"),
                                ("full", "Full Screen"),
                            ],
                            "help_text": "Banner height on desktop",
                        },
                    ),
                    6: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 30,
                            "help_text": "Dark overlay opacity (0-100) - Helps text readability",
                            "max_value": 100,
                            "min_value": 0,
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("center", "Center"), ("right", "Right")],
                            "help_text": "Text alignment in banner",
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("white", "White"), ("black", "Black")],
                            "help_text": "Text color",
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Button text", "max_length": 50, "required": False},
                    ),
                    10: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link to internal page", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "External URL (overrides internal link)", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("image", 2),
                                ("image_tablet", 3),
                                ("image_mobile", 4),
                                ("height", 5),
                                ("overlay_opacity", 6),
                                ("text_alignment", 7),
                                ("text_color", 8),
                                ("cta_text", 9),
                                ("cta_link", 10),
                                ("cta_external", 11),
                            ]
                        ],
                        {},
                    ),
                    13: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    14: ("wagtail.blocks.CharBlock", (), {"max_length": 255, "required": False}),
                    15: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    16: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    17: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 13),
                                ("title", 14),
                                ("description", 15),
                                ("link_page", 16),
                                ("link_external", 17),
                            ]
                        ],
                        {},
                    ),
                    19: ("wagtail.blocks.ListBlock", (18,), {"max_num": 10, "min_num": 2}),
                    20: ("wagtail.blocks.BooleanBlock", (), {"default": True, "required": False}),
                    21: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 5000, "help_text": "Milliseconds"},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("slides", 19),
                                ("autoplay", 20),
                                ("autoplay_speed", 21),
                                ("show_arrows", 20),
                                ("show_dots", 20),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "YouTube, Vimeo, or video file URL"},
                    ),
                    24: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Fallback image (1920x600px)"},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("video_url", 23),
                                ("poster_image", 24),
                                ("autoplay", 20),
                                ("loop", 20),
                                ("muted", 20),
                                ("show_controls", 20),
                            ]
                        ],
                        {},
                    ),
                    26: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Large background image (1920x800px)"},
                    ),
                    27: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 50,
                            "help_text": "Parallax speed (0-100)",
                            "max_value": 100,
                            "min_value": 0,
                        },
                    ),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small (400px)"),
                                ("medium", "Medium (600px)"),
                                ("large", "Large (800px)"),
                            ]
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 26),
                                ("title", 14),
                                ("subtitle", 14),
                                ("speed", 27),
                                ("height", 28),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Choose a hero section type (optional)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="no_follow",
            field=models.BooleanField(
                default=False, help_text="Prevent search engines from following links on this page"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="no_index",
            field=models.BooleanField(
                default=False, help_text="Prevent search engines from indexing this page"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image for social media sharing (1200x630px recommended)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="twitter_card_type",
            field=models.CharField(
                choices=[
                    ("summary", "Summary"),
                    ("summary_large_image", "Summary with Large Image"),
                    ("player", "Player"),
                ],
                default="summary_large_image",
                help_text="Twitter card type",
                max_length=20,
            ),
        ),
    ]
