# Generated by Django 5.1.14 on 2025-11-17 13:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_homepage_body_alter_homepage_canonical_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="body",
        ),
        migrations.AddField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("content_image_block", 13),
                    ("explore_models_block", 14),
                    ("model_cards_block", 17),
                    ("large_banner_block", 18),
                    ("content_points_block", 21),
                    ("exclusive_offer_block", 22),
                    ("news_list_swiper_block", 32),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "editor": "heading",
                            "features": [],
                            "label": "Heading",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Add your sub heading", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "editor": "default",
                            "help_text": "Add additional text",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Please upload an image",
                            "label": "Image",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [("right", "Right"), ("left", "Left")],
                            "help_text": "Image Alignment",
                            "max_length": 20,
                            "null": True,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Enter the label of the link", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("internal", "Internal Page"),
                                ("external", "External URL"),
                            ],
                            "help_text": "Select the type of link",
                        },
                    ),
                    7: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Select an internal page",
                            "page_type": [],
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "Enter an external URL", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Add the tab key", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 5),
                                ("link_type", 6),
                                ("internal_page", 7),
                                ("external_url", 8),
                                ("tab_key", 9),
                            ]
                        ],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.ListBlock",
                        (10,),
                        {
                            "help_text": "Add button/link information to this section",
                            "label": "Add link details",
                            "max_num": 2,
                            "min_num": 0,
                        },
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("transparent", "Transparent Background"),
                                ("solid-blue", "Solid Blue Background"),
                                ("solid-gray", "Solid Grey Background"),
                                ("gradient", "Gradient Background"),
                                ("pattern", "Pattern Background"),
                            ],
                            "help_text": "Block Background",
                            "max_length": 50,
                            "null": True,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("sub_heading", 1),
                                ("description", 2),
                                ("image", 3),
                                ("image_alignment", 4),
                                ("links", 11),
                                ("background", 12),
                            ]
                        ],
                        {"group": "Base Blocks"},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("main_heading", 0),
                                ("heading", 0),
                                ("sub_heading", 1),
                                ("description", 2),
                                ("image", 3),
                                ("links", 11),
                                ("background", 12),
                            ]
                        ],
                        {"group": "Base Blocks"},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("description", 2),
                                ("image", 3),
                                ("links", 11),
                                ("background", 12),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.ListBlock",
                        (15,),
                        {
                            "help_text": "Add models cards to this section",
                            "label": "Add Model Cards",
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("sub_heading", 1),
                                ("description", 2),
                                ("links", 11),
                                ("background", 12),
                                ("points", 16),
                            ]
                        ],
                        {"group": "Base Blocks"},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("sub_heading", 1),
                                ("description", 2),
                                ("image", 3),
                                ("links", 11),
                                ("background", 12),
                            ]
                        ],
                        {"group": "Base Blocks"},
                    ),
                    19: ("wagtail.blocks.StructBlock", [[("heading", 0), ("description", 2)]], {}),
                    20: (
                        "wagtail.blocks.ListBlock",
                        (19,),
                        {"help_text": "Add points to this section", "label": "Add Points"},
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("description", 2),
                                ("image", 3),
                                ("points", 20),
                                ("links", 11),
                                ("background", 12),
                            ]
                        ],
                        {"group": "Base Blocks"},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("description", 2), ("links", 11), ("background", 12)]],
                        {"group": "Base Blocks"},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Add your heading", "required": False},
                    ),
                    24: (
                        "wagtail.blocks.ListBlock",
                        (10,),
                        {
                            "help_text": "Add button/link information to this section",
                            "label": "Add link details",
                            "min_num": 0,
                        },
                    ),
                    25: ("core.blocks.content_blocks.NewsChooserBlock", (), {}),
                    26: (
                        "wagtail.blocks.ListBlock",
                        (25,),
                        {"label": "Choose the news to display."},
                    ),
                    27: ("wagtail.blocks.StructBlock", [[("news", 26)]], {}),
                    28: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 0,
                            "help_text": "Maximum number of items to display (set to zero for full list of items).",
                        },
                    ),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("title", "Title"),
                                ("date", "Date"),
                                ("path", "Sort Order"),
                            ],
                            "help_text": "Select how to sort the items",
                        },
                    ),
                    30: ("wagtail.blocks.StructBlock", [[("max_items", 28), ("order_by", 29)]], {}),
                    31: (
                        "wagtail.blocks.StreamBlock",
                        [[("choose_news", 27), ("list_all_news", 30)]],
                        {
                            "default_value": [
                                {
                                    "type": "list_all",
                                    "value": {"items_per_page": 10, "order_by": "date"},
                                }
                            ],
                            "label": "List the news",
                            "max_num": 1,
                            "required": True,
                        },
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 23),
                                ("description", 2),
                                ("background", 12),
                                ("view_more_page", 24),
                                ("listing_options", 31),
                            ]
                        ],
                        {"group": "Base Blocks"},
                    ),
                },
                help_text="Main page content",
            ),
        ),
    ]
